### ISSUE TITLE
Latex mathematical expressions rendered as text

### ISSUE THREAD

**Issue by David548219** [max-heller/mdbook-pandoc#164]
Hello!

Attempting to use latex equations in the book.

Markdown file contents:

```md
# Computed {#computed}

$$I(x)=I_0e^{-ax}.$$

```

And is translated into:

```
[Header 1 ("computed", [], []) [Str "Computed"], Para [Str "$$I(x)=I_0e^{-ax}.$$"]]
```

This is mkbook-pandoc related part of book.toml:

```toml
[output.pandoc.profile.pdf]
output-file = "output.pdf"
to = "latex"
pdf-engine = "xelatex"

[output.pandoc.profile.pdf.variables]
#documentclass = "book"
mainfont = "Times New Roman"
mathfont = "TeX Gyre Schola Math"
colorlinks = true
geometry = "a4paper"
```

<details>
  <summary>The resulting pdf from mdbook build</summary>
  <img src=https://github.com/user-attachments/assets/152a8a84-9d84-48fb-869e-f65c97ac0718 />
</details>

<details>
  <summary>The resulting pdf from using pandoc directly with command:</summary>
  <img src=https://github.com/user-attachments/assets/05ff72bf-9848-4993-957d-17d9e3040e74 />
</details>

```bash
pandoc --pdf-engine=xelatex cdb-book/src/bnpl/computed.md -V geometry:a4paper -V geometry:margin=2cm -s  -o a.pdf -V mainfont='Times New Roman' -V colorlinks=true --number-sections
```

Am I using correct configuration for math expression parsing? Using different latex engines and versions yields the same result as listed above, which leads me to believe the issue is higher up the chain.

Versions:
mdbook 0.4.44
mdbook-pandoc 0.9.3
pandoc 3.6.3
XeTeX 3.141592653-2.6-0.999993

**Comment by max-heller** [comment]
Hello!

`mdbook-pandoc` currently doesn't support mathematical expressions. This comes down to the version of `pulldown-cmark` that `mdbook-pandoc` and `mdbook` use for parsing markdown not supporting parsing math. Newer versions of `pulldown-cmark` have added support for math, which should make it straightforward to generate Pandoc math inlines/blocks, but I've been holding off on upgrading because `mdbook` is stuck on upgrading until it wants to make a breaking 0.5 release. Given that math and several other features are blocked on this, I may end up upgrading `mdbook-pandoc`'s `pulldown-cmark` dependency before `mdbook` does, but it'd be nice to know which of the new features `mdbook` intends to support so `mdbook-pandoc` can behave consistently. (In particular, note that your example does not render as math in `mdbook`'s default HTML renderer, see [here](https://rust-lang.github.io/mdBook/format/mathjax.html).)

**Comment by max-heller** [comment]
I decided to upgrade `pulldown-cmark` before `mdbook` does, leaving the new features off by default. As of #166, `mdbook-pandoc` supports math like your example, you just need to enable an option:
```toml
[output.pandoc.markdown.extensions]
math = true
```
